### ISSUE TITLE
Rename to simple_character_controller

### ISSUE THREAD

**Issue by trundlr** [Small-Fish-Dev/shrimple_character_controller#1]
The name shrimple is misleading. I do not see any shrimp in this repository, and the character controller does not seem to be specific to a shrimp.

**Comment by CyberAgentz** [comment]
SHRIMP are a PLANNED feature

**Comment by wheatleymf** [comment]
Hello trundler, thank you for making an issue.

I have reviewed your problem and identified the cause of this issue. I am rolling out a new update with a fix that will be uploaded to production sometime today. Here's a related commit that you can review: https://github.com/Small-Fish-Dev/shrimple_character_controller/commit/45bdda48c6713713a7b5411853cad795c59eccf2

From now on, we are shipping Shrimple Character Controller with a picture of a shrimp that can be found in `Assets/prefabs/` folder. This change has been already approved by @yuberee and the rest of Small Fish management team. 

- wheatleymf

**Comment by trundlr** [comment]
This is amazing work! Thank you!
