### ISSUE TITLE
Walking up stairs is sluggish/delayed?

### ISSUE THREAD

**Issue by IMCraytex** [Small-Fish-Dev/shrimple_character_controller#4]
So essentially walking up stairs will sometimes be delayed, What i mean by this is you hit the step. you stop then you step up, Losing that precious velocity. This is also very noticeable when walking up a slanted step you will walk along the step before walking up it.

**Comment by yuberee** [comment]
Might be something with the latest change, while I look at this I'll make an option to keep full velocity on stairs.

**Comment by IMCraytex** [comment]
Cheers, Whenever you push the change I will do some tests

**Comment by yuberee** [comment]
Fixed!
I was checking for steps starting from the current position rather than the collision position, so if your velocity was higher than the minimum step depth it would look for, it wouldn't find a step and defaulted to the collision being a wall, slowing you down.
